# Generated by Django 3.2.3 on 2021-05-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
